apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: {{ .Values.appName }}
spec:
  rules:
  - host: {{ .Values.appName }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.serviceName }}
            port:
              number: {{ .Values.sourcePort }}
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
