apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.serviceName }}
spec:
  ports:
  - name: http
    port: {{ .Values.sourcePort }}
    protocol: TCP
    targetPort: {{ .Values.sourcePort }}
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
status:
  loadBalancer: {}
